-- MySQL Script generated by MySQL Workbench
-- Thu May 28 18:36:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`klijent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`klijent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`klijent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `OIB` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefon` VARCHAR(15) NOT NULL,
  `ulica_i_kucni_broj` VARCHAR(100) NOT NULL,
  `postanski_broj` VARCHAR(6) NOT NULL,
  `mjesto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `OIB_UNIQUE` (`OIB` ASC) VISIBLE,
  UNIQUE INDEX `telefon_UNIQUE` (`telefon` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banka`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`banka` ;

CREATE TABLE IF NOT EXISTS `mydb`.`banka` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(255) NOT NULL,
  `swift_kod` VARCHAR(11) NOT NULL,
  `ulica_i_kucni_broj` VARCHAR(100) NOT NULL,
  `postanski_broj` VARCHAR(6) NOT NULL,
  `mjesto` VARCHAR(100) NOT NULL,
  `oib` CHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ime_UNIQUE` (`ime` ASC) VISIBLE,
  UNIQUE INDEX `swift_kod_UNIQUE` (`swift_kod` ASC) VISIBLE,
  UNIQUE INDEX `oib_UNIQUE` (`oib` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`investicijski_racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`investicijski_racun` ;

CREATE TABLE IF NOT EXISTS `mydb`.`investicijski_racun` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `klijent_id` INT NOT NULL,
  `banka_id` INT NOT NULL,
  `broj_racuna` VARCHAR(21) NOT NULL,
  `stanje` DECIMAL(38,18) NOT NULL,
  `datum_otvaranja` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `banka_id_idx` (`banka_id` ASC) VISIBLE,
  INDEX `klijent_id_idx` (`klijent_id` ASC) VISIBLE,
  UNIQUE INDEX `broj_racuna_UNIQUE` (`broj_racuna` ASC) VISIBLE,
  CONSTRAINT `fk_ir_klijent_id`
    FOREIGN KEY (`klijent_id`)
    REFERENCES `mydb`.`klijent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ir_banka_id`
    FOREIGN KEY (`banka_id`)
    REFERENCES `mydb`.`banka` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfelj`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfelj` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfelj` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `investicijski_racun_id` INT NOT NULL,
  `ime` VARCHAR(100) NOT NULL,
  `sklonost_riziku` ENUM('niska', 'srednja', 'visoka') NULL,
  `opis_portfelja` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `investicijski_racun_id_idx` (`investicijski_racun_id` ASC) VISIBLE,
  CONSTRAINT `fk_port_investicijski_racun_id`
    FOREIGN KEY (`investicijski_racun_id`)
    REFERENCES `mydb`.`investicijski_racun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tip_imovine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tip_imovine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tip_imovine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(45) NOT NULL,
  `dodatan_opis_imovine` VARCHAR(255) NULL,
  `razina_rizika` ENUM('nizak', 'srednji', 'visok') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tip_UNIQUE` (`tip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imovina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imovina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imovina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `tip_imovine_id` INT NOT NULL,
  `oznaka_imovine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ime_UNIQUE` (`ime` ASC) VISIBLE,
  INDEX `tip_imovine_id_idx` (`tip_imovine_id` ASC) VISIBLE,
  UNIQUE INDEX `oznaka_UNIQUE` (`oznaka_imovine` ASC) VISIBLE,
  CONSTRAINT `fk_imovina_tip_imovine_id`
    FOREIGN KEY (`tip_imovine_id`)
    REFERENCES `mydb`.`tip_imovine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tip_transakcije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tip_transakcije` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tip_transakcije` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tip` ENUM('uplata', 'isplata', 'kupnja', 'prodaja', 'dividenda') NOT NULL,
  `opis_transakcije` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tip_UNIQUE` (`tip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transakcija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transakcija` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transakcija` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `investicijski_racun_id` INT NOT NULL,
  `imovina_id` INT NOT NULL,
  `tip_transakcije_id` INT NOT NULL,
  `kolicina` DECIMAL(38,18) UNSIGNED NOT NULL,
  `cijena` DECIMAL(38,18) UNSIGNED NOT NULL,
  `naknada` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `investicijski_racun_id_idx` (`investicijski_racun_id` ASC) VISIBLE,
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  INDEX `tip_transakcije_id_idx` (`tip_transakcije_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_investicijski_racun_id`
    FOREIGN KEY (`investicijski_racun_id`)
    REFERENCES `mydb`.`investicijski_racun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_tip_transakcije_id`
    FOREIGN KEY (`tip_transakcije_id`)
    REFERENCES `mydb`.`tip_transakcije` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `chk_kolicina_non_negative`
    CHECK (`kolicina` >= 0),
  CONSTRAINT `chk_cijena_non_negative`
    CHECK (`cijena` >= 0))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfelj_imovina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfelj_imovina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfelj_imovina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `portfelj_id` INT NOT NULL,
  `imovina_id` INT NOT NULL,
  `kolicina` DECIMAL(38,18) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `portfelj_id_idx` (`portfelj_id` ASC) VISIBLE,
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  UNIQUE INDEX `uniq_pi` (`portfelj_id` ASC, `imovina_id` ASC) VISIBLE,
  CONSTRAINT `fk_pi_portfelj_id`
    FOREIGN KEY (`portfelj_id`)
    REFERENCES `mydb`.`portfelj` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pi_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`povijesna_cijena_imovine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`povijesna_cijena_imovine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`povijesna_cijena_imovine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imovina_id` INT NOT NULL,
  `cijena` DECIMAL(38,18) UNSIGNED NOT NULL,
  `datum` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  CONSTRAINT `fk_pci_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
