-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 19:30:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`klijenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`klijenti` ;

CREATE TABLE IF NOT EXISTS `mydb`.`klijenti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `OIB` VARCHAR(11) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `OIB_UNIQUE` (`OIB` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`banke`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`banke` ;

CREATE TABLE IF NOT EXISTS `mydb`.`banke` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ime_UNIQUE` (`ime` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`investicijski_racuni`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`investicijski_racuni` ;

CREATE TABLE IF NOT EXISTS `mydb`.`investicijski_racuni` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `klijent_id` INT NOT NULL,
  `banka_id` INT NOT NULL,
  `broj_racuna` VARCHAR(21) NOT NULL,
  `stanje` DECIMAL(38,18) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `banka_id_idx` (`banka_id` ASC) VISIBLE,
  INDEX `klijent_id_idx` (`klijent_id` ASC) VISIBLE,
  UNIQUE INDEX `broj_racuna_UNIQUE` (`broj_racuna` ASC) VISIBLE,
  CONSTRAINT `fk_ir_klijent_id`
    FOREIGN KEY (`klijent_id`)
    REFERENCES `mydb`.`klijenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ir_banka_id`
    FOREIGN KEY (`banka_id`)
    REFERENCES `mydb`.`banke` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfelji`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfelji` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfelji` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `investicijski_racun_id` INT NOT NULL,
  `ime` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `investicijski_racun_id_idx` (`investicijski_racun_id` ASC) VISIBLE,
  CONSTRAINT `fk_port_investicijski_racun_id`
    FOREIGN KEY (`investicijski_racun_id`)
    REFERENCES `mydb`.`investicijski_racuni` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uplate_isplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`uplate_isplate` ;

CREATE TABLE IF NOT EXISTS `mydb`.`uplate_isplate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `investicijski_racun_id` INT NOT NULL,
  `iznos` DECIMAL(38,18) UNSIGNED NOT NULL,
  `tip` ENUM("uplata", "isplata") NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `investicijski_racun_id_idx` (`investicijski_racun_id` ASC) VISIBLE,
  CONSTRAINT `fk_ui_investicijski_racun_id`
    FOREIGN KEY (`investicijski_racun_id`)
    REFERENCES `mydb`.`investicijski_racuni` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tip_imovine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tip_imovine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tip_imovine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tip_UNIQUE` (`tip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imovina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`imovina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`imovina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `tip_imovine_id` INT NOT NULL,
  `trenutna_cijena` DECIMAL(38,18) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ime_UNIQUE` (`ime` ASC) VISIBLE,
  INDEX `tip_imovine_id_idx` (`tip_imovine_id` ASC) VISIBLE,
  CONSTRAINT `fk_imovina_tip_imovine_id`
    FOREIGN KEY (`tip_imovine_id`)
    REFERENCES `mydb`.`tip_imovine` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tip_transakcije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tip_transakcije` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tip_transakcije` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tip_UNIQUE` (`tip` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transakcije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transakcije` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transakcije` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `investicijski_racun_id` INT NOT NULL,
  `imovina_id` INT NOT NULL,
  `tip_transakcije_id` INT NOT NULL,
  `kolicina` DECIMAL(38,18) UNSIGNED NOT NULL,
  `cijena` DECIMAL(38,18) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `investicijski_racun_id_idx` (`investicijski_racun_id` ASC) VISIBLE,
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  INDEX `tip_transakcije_id_idx` (`tip_transakcije_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_investicijski_racun_id`
    FOREIGN KEY (`investicijski_racun_id`)
    REFERENCES `mydb`.`investicijski_racuni` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_tip_transakcije_id`
    FOREIGN KEY (`tip_transakcije_id`)
    REFERENCES `mydb`.`tip_transakcije` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfelj_imovina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfelj_imovina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfelj_imovina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `portfelj_id` INT NOT NULL,
  `imovina_id` INT NOT NULL,
  `kolicina` DECIMAL(38,18) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `portfelj_id_idx` (`portfelj_id` ASC) VISIBLE,
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  UNIQUE INDEX `uniq_pi` (`portfelj_id` ASC, `imovina_id` ASC) VISIBLE,
  CONSTRAINT `fk_pi_portfelj_id`
    FOREIGN KEY (`portfelj_id`)
    REFERENCES `mydb`.`portfelji` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pi_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`povijesne_cijene_imovine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`povijesne_cijene_imovine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`povijesne_cijene_imovine` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imovina_id` INT NOT NULL,
  `cijena` DECIMAL(38,18) UNSIGNED NOT NULL,
  `datum` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  CONSTRAINT `fk_pci_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dividende`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dividende` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dividende` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imovina_id` INT NOT NULL,
  `iznos` DECIMAL(38,18) UNSIGNED NOT NULL,
  `datum_isplate` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `imovina_id_idx` (`imovina_id` ASC) VISIBLE,
  CONSTRAINT `fk_d_imovina_id`
    FOREIGN KEY (`imovina_id`)
    REFERENCES `mydb`.`imovina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
